# Generated by Django 4.2 on 2023-05-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsustentable', '0002_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('FotoNoticia', models.ImageField(upload_to=None)),
                ('Titulo', models.TextField(max_length=500)),
                ('Mensaje', models.TextField(max_length=500)),
                ('id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('admid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsustentable.administrador')),
            ],
        ),
    ]
